### ISSUE TITLE
code review 1

### ISSUE THREAD

**Issue by salma77** [mahmoudyusof/cracking_the_coding_interview#1]
# Data Structures
### Good
- well-documented
- effective using of newly learned concepts (Bit vectors and string builders)

### Bad
- why the ///////////END sth////////////
- `compressString()`(line 215, ArraysAndStrings.java) function fails at characters repeated more than 9 times

### Good
- Smart test cases
- well-modularized
- well-written docstrings 

### Bad
- Test nodes using assertSame, instead of only asserting the value which the node holds using assertEquals
- names in `testGetIntersectionNode()` (line 361, LinkedLists.java) are unclear

### Good
- well-modularized (StackNode is separate from MyStack)
- naming conventions are great

### Bad
- only 1 test case (AND it. is. the. basic. case. c'mon man)
- special classes (like MyMinStack and MultiStack) need proper documentation, at least add docstrings

### Good
- well-modularized
- effective use of helper functions (makes code better to understand)

### Bad
- redundant functions (`insert` in BinarySearchTree and BinarySearchTreeNode)
- `testMakeMinHeightTree()` fails when you add the same element more than once
- more corner cases when testing
- docstrings ya afandy

**Comment by mahmoudyusof** [comment]
Thanks for the useful comment, I've fixed almost all of the issues mentioned here, please check if we can close this issue.
> **NOTE:** In chapter4 graphs and trees, testMakeMinHeightTree works with duplicated values, can you please tell me the exact test case that fails?
